// app/api/sessions/[id]/output/[filename]/route.ts
//
// GET /api/sessions/:id/output/:filename
//
// Serves output artifacts (Plotly HTML, images) generated by code execution.
// These files live at uploads/<sessionId>/output/<filename> on disk.
// The frontend renders Plotly HTML files in iframes via this route.

import { NextRequest } from "next/server";
import { readFile } from "fs/promises";
import { join } from "path";
import { existsSync } from "fs";

// Content-type mapping for common output formats
const CONTENT_TYPES: Record<string, string> = {
  ".html": "text/html",
  ".png": "image/png",
  ".jpg": "image/jpeg",
  ".jpeg": "image/jpeg",
  ".svg": "image/svg+xml",
  ".csv": "text/csv",
  ".json": "application/json",
};

export async function GET(
  _req: NextRequest,
  { params }: { params: Promise<{ id: string; filename: string }> }
) {
  const { id: sessionId, filename } = await params;

  // Prevent path traversal — filename must not contain slashes or ..
  if (filename.includes("..") || filename.includes("/")) {
    return new Response("Invalid filename", { status: 400 });
  }

  const filePath = join(process.cwd(), "uploads", sessionId, "output", filename);

  if (!existsSync(filePath)) {
    return new Response("Not found", { status: 404 });
  }

  const buffer = await readFile(filePath);
  const ext = "." + filename.split(".").pop()?.toLowerCase();
  const contentType = CONTENT_TYPES[ext] ?? "application/octet-stream";

  return new Response(buffer, {
    headers: { "Content-Type": contentType },
  });
}
